Add four OGC templates
metanorma/mn-templates-ogc pull request #30
Opened 2020-07-05 16:27 UTC by manuel489

*From https://github.com/metanorma/mn-templates-ogc/issues/12*

Added: `primer`, `policy`, `reference-model`, and `user-guide` templates.

I believe these are the last ones regarding OGC flavor.

Thanks!

2020-07-05 17:45 UTC, ronaldtse requested changes

2020-07-05 17:45 UTC, ronaldtse commented on other-primer/sections/03-terms_and_definitions.adoc
> +== Terms and Definitions
"Terms and definitions"

2020-07-05 17:45 UTC, ronaldtse commented on other-primer/sections/02-norm-refs.adoc
> +== Normative and Informative References
"Normative references", no "Informative references" here.

2020-07-05 18:31 UTC, manuel489 commented on other-primer/sections/03-terms_and_definitions.adoc
> +== Terms and Definitions
Fixed

2020-07-05 18:31 UTC, manuel489 commented on other-primer/sections/02-norm-refs.adoc
> +== Normative and Informative References
Fixed

2020-07-06 00:33 UTC, ronaldtse commented
Thanks @manuel489 !

2020-07-06 00:33 UTC, merged